#!/usr/bin/env node
// record-tape.js — (re)record the golden per-tick hashes for the input tape.
//
// This lives outside test/ on purpose. A bare `node --test` (and most IDE test
// runners) sweeps in every file under test/, which would execute the recorder
// and silently rewrite the very baseline test/golden-tape.test.js checks
// against — leaving the regression test passing vacuously forever.
//
//   npm run tape:record
import { readFileSync, writeFileSync } from 'node:fs';
import { runTape } from '../test/harness/tape.js';

// one-round: 600 ticks of a quiet, unresolved round — the fine-grained oracle
//   for the update phase itself.
// three-rounds: 4,200 ticks that die, run the killcam, resolve the round on the
//   tick scheduler and load the next map, several times over. The input half is
//   generated by scripts/make-long-tape.js.
//
// THE SEEDS ARE PER TAPE, AND THE LONG ONE IS NOT 12345. How many rounds the
// long tape resolves inside its 4,200 ticks is wildly seed-sensitive, because a
// round ends when two wizards marching a fixed pattern happen to finish each
// other off. Reseeding a fixture to keep a guard green is exactly the shape of a
// bad edit, so here is the measurement rather than an assurance. Round counts
// for seeds 12345..12360, before and after task 9:
//
//   before  4 1 4 5 2 1 1 2 1 2 1 1 1 1 4 1
//   after   1 1 2 5 1 1 1 3 1 2 2 1 1 2 3 1
//
// 12345 was a 4-round run; once task 9 stopped projectiles spawning inside walls
// the same seed landed on a 1-round run, and test/golden-tape.test.js's
// round-crossing guard (`rounds >= 3`) went red. 12348 is the lowest seed from
// 12345 up that still crosses four rounds, leaving a round of margin.
//
// That the sim did not get less lethal is a separate claim, and it was measured
// separately, over seeds 1..40: mean rounds 2.200 before, 2.225 after, range
// 1..5 in both. The distribution is unchanged; 12345 simply drew badly after the
// reshuffle. Do not copy this reseed without repeating that scan — the scan is
// the load-bearing part, not the new number.
//
// The short tape keeps 12345 so its golden moves for behaviour alone.
const TAPES = [
  { name: 'one-round', ticks: 600, seed: 12345 },
  { name: 'three-rounds', ticks: 4200, seed: 12348 },
];

for (const { name, ticks, seed } of TAPES) {
  const tape = JSON.parse(readFileSync(`test/tape/${name}.input.json`, 'utf8'));
  const hashes = runTape({ tape, ticks, seed });
  writeFileSync(`test/tape/${name}.golden.json`, JSON.stringify({ ticks, seed, hashes }, null, 0) + '\n');
  console.log(`${name}: recorded ${hashes.length} tick hashes; last = ${hashes.at(-1)}`);
}
