#!/usr/bin/env node
// record-tape.js — (re)record the golden per-tick hashes for the input tape.
//
// This lives outside test/ on purpose. A bare `node --test` (and most IDE test
// runners) sweeps in every file under test/, which would execute the recorder
// and silently rewrite the very baseline test/golden-tape.test.js checks
// against — leaving the regression test passing vacuously forever.
//
//   npm run tape:record
import { readFileSync, writeFileSync } from 'node:fs';
import { runTape } from '../test/harness/tape.js';

// one-round: 600 ticks of a quiet, unresolved round — the fine-grained oracle
//   for the update phase itself. It genuinely stays in round 1.
// three-rounds: 4,200 ticks that die, run the killcam, resolve the round on the
//   tick scheduler and load the next map, several times over. The input half is
//   generated by scripts/make-long-tape.js.
//
// `three-rounds` IS A HISTORICAL NAME: at its current seed the tape crosses
// FIVE rounds, not three (the task 13 note below is where that number comes
// from — 12353 was chosen for being the lowest seed that crossed five). The
// files are not renamed to match, because the name appears in both goldens'
// paths and renaming them would rewrite two recorded baselines to say nothing
// new. Read it as "the long tape". The guard in test/golden-tape.test.js is
// `rounds >= 3`, a floor, so the drift between name and reality costs nothing
// beyond this paragraph.
//
// THE SEEDS ARE PER TAPE, AND THE LONG ONE IS NOT 12345. How many rounds the
// long tape resolves inside its 4,200 ticks is wildly seed-sensitive, because a
// round ends when two wizards marching a fixed pattern happen to finish each
// other off. Reseeding a fixture to keep a guard green is exactly the shape of a
// bad edit, so here is the measurement rather than an assurance.
//
// TASK 9 moved it from 12345 to 12348. Round counts, seeds 12345..12360:
//
//   before  4 1 4 5 2 1 1 2 1 2 1 1 1 1 4 1
//   after   1 1 2 5 1 1 1 3 1 2 2 1 1 2 3 1
//
// 12345 was a 4-round run; once task 9 stopped projectiles spawning inside walls
// the same seed landed on a 1-round run. 12348 was the lowest seed from 12345 up
// that still crossed four rounds.
//
// TASK 13 moved it again, from 12348 to 12353, for a bigger version of the same
// reshuffle: cosmetics stopped drawing from the round stream, so every gameplay
// roll after the first spark shifted. 12348 became a 1-round run. Round counts,
// seeds 12348..12363, before and after:
//
//   before  4 1 1 1 3 1 2 2 1 1 2 3 1 4 1 3
//   after   1 2 3 1 1 5 2 4 2 1 1 3 3 3 3 1
//
// 12353 is the lowest seed from 12348 up that crosses five rounds — two rounds
// of margin on the `rounds >= 3` guard.
//
// That the sim did not get less lethal is a separate claim, measured separately
// over seeds 1..400: mean rounds 2.152 before, 2.170 after; range 1..5 before,
// 1..6 after. (The first 120 seeds alone read 2.183 vs 1.950, which is the size
// of swing 120 samples of a 1..6 variable produce on their own — hence 400.)
// The distribution is unchanged; 12348 simply drew badly after the reshuffle.
// Do not copy this reseed without repeating that scan — the scan is the
// load-bearing part, not the new number.
//
// THE SPAWN-SAFETY TASK MOVED IT AGAIN, 12353 -> 12372, the third instance of
// the same reshuffle. The escape analysis nudges or relocates any spawn a
// wizard cannot get out of, so nearly every round now opens from a slightly
// different place; 12353 fell from five rounds to two, under the floor.
// Round counts, seeds 12353..12372, before and after:
//
//   before  5 2 4 2 1 1 3 3 3 3 1 3 1 2 1 1 . . . .
//   after   2 1 2 4 1 1 2 4 3 3 3 2 1 1 3 2 1 1 1 6
//
// 12372 is the lowest seed from 12353 up that crosses five; it crosses six, so
// the `rounds >= 3` guard keeps three rounds of margin.
//
// And the separate claim — that the sim did not get less lethal — measured over
// seeds 1..400 as the note above insists, rather than asserted:
//
//   before  mean 2.170, range 1..6
//   after   mean 2.083, range 1..6
//
// Rounds get slightly LONGER on average (a 4% drop in rounds-per-tape), which
// is the expected direction and the point of the change: wizards that used to
// open a round already falling out of the world now land somewhere they can
// fight from, so fewer rounds resolve inside 4,200 ticks. The range is
// unchanged. Fewer rounds here is the fix working, not the sim going quiet —
// and 12353 in particular drew badly, as 12348 did before it.
//
// AND AGAIN, 12372 -> 12392, for opening loadouts. Every wizard now starts the
// round armed, so fights begin at once instead of after a scramble for the
// first tome; 12372 fell to a 1-round run. Round counts, seeds 12372..12392:
//
//   before  6 1 1 1 4 2 1 2 4 1 2 1 1 3 1 1 3 3 1 1 .
//   after   1 3 4 1 1 4 3 2 1 3 1 3 3 3 2 2 3 2 2 1 5
//
// 12392 is the lowest seed from 12372 up that crosses five.
//
// The lethality scan over seeds 1..400 moved in the OPPOSITE direction to the
// spawn-safety change, and should have: mean rounds 2.083 -> 2.553, range 1..6
// both. Rounds resolve faster because nobody spends the opening ten seconds
// running at an unarmed opponent. That is the feature, measured.
//
// The short tape keeps 12345 so its golden moves for behaviour alone.
const TAPES = [
  { name: 'one-round', ticks: 600, seed: 12345 },
  { name: 'three-rounds', ticks: 4200, seed: 12392 },
];

for (const { name, ticks, seed } of TAPES) {
  const tape = JSON.parse(readFileSync(`test/tape/${name}.input.json`, 'utf8'));
  const hashes = runTape({ tape, ticks, seed });
  writeFileSync(`test/tape/${name}.golden.json`, JSON.stringify({ ticks, seed, hashes }, null, 0) + '\n');
  console.log(`${name}: recorded ${hashes.length} tick hashes; last = ${hashes.at(-1)}`);
}
