#!/usr/bin/env node
// record-tape.js — (re)record the golden per-tick hashes for the input tape.
//
// This lives outside test/ on purpose. A bare `node --test` (and most IDE test
// runners) sweeps in every file under test/, which would execute the recorder
// and silently rewrite the very baseline test/golden-tape.test.js checks
// against — leaving the regression test passing vacuously forever.
//
//   npm run tape:record
import { readFileSync, writeFileSync } from 'node:fs';
import { runTape } from '../test/harness/tape.js';

// one-round: 600 ticks of a quiet, unresolved round — the fine-grained oracle
//   for the update phase itself.
// three-rounds: 4,200 ticks that die, run the killcam, resolve the round on the
//   tick scheduler and load the next map, several times over. The input half is
//   generated by scripts/make-long-tape.js.
//
// THE SEEDS ARE PER TAPE, AND THE LONG ONE IS NOT 12345. How many rounds the
// long tape resolves inside its 4,200 ticks is wildly seed-sensitive — measured
// across twelve seeds it ranges from 1 to 5 — because a round ends when two
// wizards marching a fixed pattern happen to finish each other off. 12345 was a
// 4-round run until task 9 made projectiles stop spawning inside walls; the same
// seed then landed on a 1-round run and test/golden-tape.test.js's
// round-crossing guard went red. The seed is a fixture parameter, not a result:
// it is the lowest seed from 12345 up that crosses at least four rounds, which
// leaves a round of margin over the guard's `>= 3`. (Lethality itself did not
// change — the mean round count over those twelve seeds is identical before and
// after.) The short tape keeps 12345 so its golden moves for behaviour alone.
const TAPES = [
  { name: 'one-round', ticks: 600, seed: 12345 },
  { name: 'three-rounds', ticks: 4200, seed: 12348 },
];

for (const { name, ticks, seed } of TAPES) {
  const tape = JSON.parse(readFileSync(`test/tape/${name}.input.json`, 'utf8'));
  const hashes = runTape({ tape, ticks, seed });
  writeFileSync(`test/tape/${name}.golden.json`, JSON.stringify({ ticks, seed, hashes }, null, 0) + '\n');
  console.log(`${name}: recorded ${hashes.length} tick hashes; last = ${hashes.at(-1)}`);
}
